name: PlayerCompass
version: '${project.version}'
main: dev.michaud.greenpanda.playercompass.PlayerCompass
api-version: 1.19
authors: [ PandaDev ]
depend: [ GreenPandaCore ]
description: Adds a player compass that can be used to find other players