name: ExplorersToolkit
version: '${project.version}'
main: dev.michaud.greenpanda.explorerstoolkit.ExplorersToolkit
api-version: 1.19
authors: [ PandaDev ]
depend: [ GreenPandaCore ]
description: Makes it much easier and viable to explore without using the F3 menu for navigation